#ERROR MESSAGES
DEPARTMENT_ERROR_MESSAGE = '''Invald Department, see valid departments at
http://openaccess-api.clevelandart.org/#appendix-a'''

TYPE_ERROR_MESSAGE = '''Invald type, see valid types at
http://openaccess-api.clevelandart.org/#appendix-b'''

CC0_ERROR_MESSAGE = "cc0 argument must be 1 or 0"

BAD_REQUEST = lambda a: "Bad Request Status Code %s" % (a)

#VALID TYPE
VALID_PARAMETERS = [
"q",
"cc0",
"copyrighted",
"department",
"type",
"has_image",
"indent",
"skip",
"limit",
"artists",
"title",
"medium",
"credit",
"catalogue_raisonne",
"provenance",
"citations",
"exhibition_history",
"created_before",
"created_after",
"currently_on_loan",
"currently_on_view",
"african_american_artists",
"cia_alumni_artists",
"may_show_artists",
"female_artists",
"recently_acquired",
"nazi_era_provenance",
"created_after_age",
"created_before_age",
]

NO_ARGUMENT = [
"cc0",
"copyrighteed",
"currently_on_view",
"currently_on_loan",
"african_american_artists",
"cia_alumni_artists",
"may_show_artists",
"female_artists",
"recently_acquired",
"nazi_era_provenance",
"currently_on_view",
]


VALID_DEPARTMENTS = [
"African Art",
"American Painting and Sculpture",
"Art of the Americas",
"Chinese Art",
"Contemporary Art",
"Decorative Art and Design",
"Drawings",
"Egyptian and Ancient Near Eastern Art",
"European Painting and Sculpture",
"Greek and Roman Art",
"Indian and South East Asian Art",
"Islamic Art",
"Japanese Art",
"Korean Art",
"Medieval Art",
"Modern European Painting and Sculpture",
"Oceania",
"Performing Arts, Music, & Film",
"Photography",
"Prints",
"Textiles",
]

VALID_TYPES = [
"Amulets",
"Apparatus",
"Arms and Armor",
"Basketry",
"Book Binding",
"Bound Volume",
"Calligraphy",
"Carpet",
"Ceramic",
"Coins",
"Cosmetic Objects",
"Drawing",
"Embroidery",
"Enamel",
"Forgery",
"Frame",
"Funerary Equipment",
"Furniture and woodwork",
"Garment",
"Glass",
"Glyptic",
"Illumination",
"Implements",
"Inlays",
"Ivory",
"Jade",
"Jewelry",
"Knitting",
"Lace",
"Lacquer",
"Leather",
"Linoleum Block",
"Lithographic Stone",
"Manuscript",
"Metalwork",
"Miniature",
"Miscellaneous",
"Mixed Media",
"Monotype",
"Mosaic",
"Musical Instrument",
"Netsuke",
"Painting",
"Papyri",
"Photograph",
"Plaque",
"Plate",
"Portfolio",
"Portrait Miniature",
"Print",
"Relief",
"Rock crystal",
"Rubbing",
"Sampler",
"Scarabs",
"Sculpture",
"Seals",
"Silver",
"Spindle Whorl",
"Stencil",
"Stone",
"Tapestry",
"Textile",
"Time-based Media",
"Tool",
"Velvet",
"Vessels",
"Wood",
"Woodblock",
]
